/* ============================================================
   studydata.js — 家庭学習アプリの問題プール（1年4章 比例と反比例 試作）
   index.html（生徒）/ analyze.html（先生）共通。採点は engine.js。

   単元（unit）＝ 演習プリントのめあて（4章1〜8限目）にそろえてある。
   難易度（level）＝ 基本 / 標準 / 応用 の3段階。
   「難しい問題にチャレンジしたか」は level==="応用" を解いた数で見る。

   1問:
     { id, unit, level, prompt, hint?,
       type:"input"|"choice", choices?,
       subs:[ {lb?, prompt?, mode?, a} ],   // input: mode=expr|num|ineq|coord|text
       sol, src }
   出典: WS=演習プリント / p_pr=pipeline/p_pr / applied=応用チャレンジ(applied/) / 自作
   ============================================================ */

const UNITS = [
  { id:"M1-04-1", no:"4章1限目", short:"関数と変域",           name:"関数であるか正しく判断できるようになろう！" },
  { id:"M1-04-2", no:"4章2限目", short:"比例の式",             name:"比例の関係について調べよう！" },
  { id:"M1-04-3", no:"4章3限目", short:"座標",                 name:"座標をかいたり、読み取ったりできるようになろう！" },
  { id:"M1-04-4", no:"4章4限目", short:"比例のグラフ",         name:"比例のグラフを正しくかけるようになろう！" },
  { id:"M1-04-5", no:"4章5限目", short:"比例のグラフ（効率）", name:"比例のグラフを効率よくかけるようになろう！" },
  { id:"M1-04-6", no:"4章6限目", short:"反比例の関係",         name:"反比例の関係について調べよう！" },
  { id:"M1-04-7", no:"4章7限目", short:"反比例の式",           name:"反比例の性質を理解し、式を求められるようになろう！" },
  { id:"M1-04-8", no:"4章8限目", short:"反比例のグラフ",       name:"反比例のグラフをかけるようになろう！" },
];

const POOL = [
  /* ===== M1-04-1 関数と変域 ===== */
  { id:"S1-b1", unit:"M1-04-1", level:"基本",
    prompt:"次の x と y の関係について、y が x の関数であるものには ○、そうでないものには × を書きなさい。",
    type:"choice", choices:["○","×"],
    subs:[
      {lb:"(1)", prompt:"1辺が x cm の正方形の面積を y cm² とする。", a:0},
      {lb:"(2)", prompt:"絶対値が x である数を y とする。", a:1},
    ],
    sol:"x を1つ決めたとき y がただ1つに決まれば関数。(1) 面積は1つに決まる→○。(2) x=3 のとき y=3, -3 の2つ→×。",
    src:"WS(L1)" },
  { id:"S1-b2", unit:"M1-04-1", level:"基本", prompt:"x が -3 より大きいとき、x の変域を不等号で表しなさい。",
    type:"input", subs:[{mode:"ineq", a:"x>-3", ph:"x>-3"}],
    sol:"「より大きい」はその数をふくまないので > を使う。x>-3。", src:"WS(L1)" },
  { id:"S1-b3", unit:"M1-04-1", level:"基本", prompt:"x が 5 以下のとき、x の変域を不等号で表しなさい。",
    type:"input", subs:[{mode:"ineq", a:"x≦5", ph:"x≦5"}],
    sol:"「以下」はその数をふくむので ≦ を使う。x≦5。", src:"WS(L1)" },
  { id:"S1-b4", unit:"M1-04-1", level:"基本", prompt:"x が -2 以上 4 以下のとき、x の変域を不等号で表しなさい。",
    type:"input", subs:[{mode:"ineq", a:"-2≦x≦4", ph:"-2≦x≦4"}],
    sol:"「以上」「以下」はどちらもその数をふくむ。-2≦x≦4。", src:"WS(L1)" },
  { id:"S1-s1", unit:"M1-04-1", level:"標準",
    prompt:"底面積 20 cm²、高さ 15 cm の円柱の容器に水を入れる。水面の高さを x cm、水の体積を y cm³ とするとき、x の変域を不等号で表しなさい。",
    type:"input", subs:[{mode:"ineq", a:"0≦x≦15", ph:"0≦x≦15"}],
    sol:"水面の高さは空のとき 0、満水のとき容器の高さ 15。0≦x≦15。", src:"自作(WS応用)" },
  { id:"S1-s2", unit:"M1-04-1", level:"標準",
    prompt:"数直線上で、-1 の点に ●（ふくむ）、3 の点に ○（ふくまない）の印がある。この2点の間の x の変域を不等号で表しなさい。",
    type:"input", subs:[{mode:"ineq", a:"-1≦x<3", ph:"-1≦x<3"}],
    sol:"● は ≦、○ は <。左端 -1 はふくむ、右端 3 はふくまない。-1≦x<3。", src:"p_pr" },
  { id:"S1-a1", unit:"M1-04-1", level:"応用",
    prompt:"「ある0以上の整数 x を 5 でわったときの余りを y とする」について、y のとりうる値は全部で何個か。",
    type:"input", subs:[{mode:"num", a:5, ph:"…個"}],
    sol:"5 でわった余りは 0,1,2,3,4 のどれか。よって 5 個。x を決めれば y はこの5個のどれかにただ1つ決まるので関数でもある。",
    src:"applied(M1-04-1)" },
  { id:"S1-a2", unit:"M1-04-1", level:"応用",
    prompt:"y は x の関数で、対応表が次のようになっている。（ア）にあてはまる数を求めなさい。\nx：1, 2, 3, 4, 5, 6\ny：1, 3, 7, 13, 21, （ア）",
    hint:"となり合う y の差に注目。", type:"input", subs:[{lb:"ア", mode:"num", a:31}],
    sol:"y の差は 2, 4, 6, 8 と2ずつ増える。次の差は 10 なので 21+10=31。（y=x²-x+1）",
    src:"applied(M1-04-1)" },

  /* ===== M1-04-2 比例の式 ===== */
  { id:"S2-b1", unit:"M1-04-2", level:"基本", prompt:"y は x に比例し、x=4 のとき y=12 です。y を x の式で表しなさい。",
    type:"input", subs:[{mode:"expr", a:"y=3x", ph:"y=…"}],
    sol:"y=ax に代入して 12=4a、a=3。y=3x。", src:"WS(L2)" },
  { id:"S2-b2", unit:"M1-04-2", level:"基本", prompt:"y は x に比例し、x=3 のとき y=-15 です。y を x の式で表しなさい。",
    type:"input", subs:[{mode:"expr", a:"y=-5x", ph:"y=…"}],
    sol:"-15=3a、a=-5。y=-5x。", src:"WS(L2)" },
  { id:"S2-b3", unit:"M1-04-2", level:"基本", prompt:"比例のグラフが点 (2, -6) を通ります。y を x の式で表しなさい。",
    type:"input", subs:[{mode:"expr", a:"y=-3x", ph:"y=…"}],
    sol:"-6=2a、a=-3。y=-3x。", src:"p_pr" },
  { id:"S2-b4", unit:"M1-04-2", level:"基本", prompt:"比例の式 y=4x について、x=-3 のときの y の値を求めなさい。",
    type:"input", subs:[{mode:"num", a:-12, ph:"y=…"}],
    sol:"y=4×(-3)=-12。", src:"WS(L2)" },
  { id:"S2-s1", unit:"M1-04-2", level:"標準",
    prompt:"下の対応表は y が x に比例する関係を表している。y を x の式で表しなさい。\nx：-4, 0, 6\ny：10, 0, -15",
    type:"input", subs:[{mode:"expr", a:"y=-5/2x", ph:"y=…"}],
    sol:"比例なので y=ax。x=-4 で y=10 だから 10=-4a、a=-5/2。y=-5/2 x。", src:"applied(M1-04-2)" },
  { id:"S2-s2", unit:"M1-04-2", level:"標準", prompt:"y は x に比例し、x=3 のとき y=-12 です。y=20 となるときの x の値を求めなさい。",
    type:"input", subs:[{mode:"num", a:-5, ph:"x=…"}],
    sol:"-12=3a、a=-4。y=-4x。20=-4x を解いて x=-5。", src:"applied(M1-04-2)" },
  { id:"S2-a1", unit:"M1-04-2", level:"応用", prompt:"y は x に比例し、x=-6 のとき y=8 です。x=15 のときの y の値を求めなさい。",
    type:"input", subs:[{mode:"num", a:-20, ph:"y=…"}],
    sol:"8=-6a、a=-4/3。y=-4/3 x。x=15 のとき y=-4/3×15=-20。", src:"applied(M1-04-2)" },
  { id:"S2-a2", unit:"M1-04-2", level:"応用", prompt:"2点 A(-4, 6)、B(m, -18) が、原点を通る同じ直線上にあります。m の値を求めなさい。",
    type:"input", subs:[{mode:"num", a:12, ph:"m=…"}],
    sol:"y=ax。A より 6=-4a、a=-3/2。-18=-3/2×m、m=12。", src:"applied(M1-04-2) / p_pr" },

  /* ===== M1-04-3 座標 ===== */
  { id:"S3-b1", unit:"M1-04-3", level:"基本", prompt:"点 A(-3, 4) は第何象限にありますか。数字（1〜4）で答えなさい。",
    type:"input", subs:[{mode:"num", a:2}],
    sol:"(-, +) は第2象限。", src:"p_pr" },
  { id:"S3-b2", unit:"M1-04-3", level:"基本", prompt:"点 (2, -5) を x 軸について対称に移動した点の座標を答えなさい。",
    type:"input", subs:[{mode:"coord", a:[2,5], ph:"( , )"}],
    sol:"x 軸について対称 → x はそのまま、y の符号が変わる。(2, 5)。", src:"WS(L3)" },
  { id:"S3-b3", unit:"M1-04-3", level:"基本", prompt:"点 (2, -5) を原点について対称に移動した点の座標を答えなさい。",
    type:"input", subs:[{mode:"coord", a:[-2,5], ph:"( , )"}],
    sol:"原点について対称 → x も y も符号が変わる。(-2, 5)。", src:"WS(L3)" },
  { id:"S3-b4", unit:"M1-04-3", level:"基本", prompt:"2点 (1, 2) と (5, 8) の中点の座標を答えなさい。",
    type:"input", subs:[{mode:"coord", a:[3,5], ph:"( , )"}],
    sol:"中点は 2点の座標のまん中。x：(1+5)/2=3、y：(2+8)/2=5。(3, 5)。", src:"WS(L3)" },
  { id:"S3-s1", unit:"M1-04-3", level:"標準", prompt:"点 A(-2, 4) と点 B(6, -2) を結ぶ線分 AB の中点の座標を答えなさい。",
    type:"input", subs:[{mode:"coord", a:[2,1], ph:"( , )"}],
    sol:"x：(-2+6)/2=2、y：(4+(-2))/2=1。(2, 1)。", src:"applied(M1-04-3)" },
  { id:"S3-s2", unit:"M1-04-3", level:"標準", prompt:"次の3点は、それぞれ第何象限にありますか。数字（1〜4）で答えなさい。",
    type:"input",
    subs:[
      {lb:"A", prompt:"A(-3, 5)", mode:"num", a:2},
      {lb:"B", prompt:"B(4, -6)", mode:"num", a:4},
      {lb:"C", prompt:"C(-2, -7)", mode:"num", a:3},
    ],
    sol:"A(-,+)＝第2、B(+,-)＝第4、C(-,-)＝第3。", src:"applied(M1-04-3) / p_pr" },
  { id:"S3-a1", unit:"M1-04-3", level:"応用",
    prompt:"3点 A(5, -2)、B(-4, -2)、C(1, 4) を頂点とする三角形 ABC の面積を求めなさい。座標の1めもりを 1 cm とします。",
    type:"input", subs:[{mode:"num", a:27, ph:"…cm²"}],
    sol:"AB は y 座標が同じなので底辺とみて AB=5-(-4)=9 cm。高さは C までの縦の距離 4-(-2)=6 cm。面積=1/2×9×6=27。",
    src:"applied(M1-04-3)" },
  { id:"S3-a2", unit:"M1-04-3", level:"応用",
    prompt:"平行四辺形 ABCD で、A(-1, -2)、B(3, -1)、C(4, 2) です。頂点 D の座標を求めなさい。",
    hint:"B→C の動きと A→D の動きは同じ。", type:"input", subs:[{mode:"coord", a:[0,1], ph:"( , )"}],
    sol:"B→C は x が +1、y が +3。D=A+(その動き)=(-1+1, -2+3)=(0, 1)。", src:"applied(M1-04-3)" },

  /* ===== M1-04-4 比例のグラフ ===== */
  { id:"S4-b1", unit:"M1-04-4", level:"基本", prompt:"比例のグラフが点 (1, 3) を通ります。y を x の式で表しなさい。",
    type:"input", subs:[{mode:"expr", a:"y=3x", ph:"y=…"}],
    sol:"3=1×a、a=3。y=3x。", src:"WS(L4)" },
  { id:"S4-b2", unit:"M1-04-4", level:"基本", prompt:"比例 y=2x のグラフ上で、x 座標が 1 である点の座標を答えなさい。",
    type:"input", subs:[{mode:"coord", a:[1,2], ph:"( , )"}],
    sol:"x=1 のとき y=2×1=2。(1, 2)。", src:"WS(L4)" },
  { id:"S4-b3", unit:"M1-04-4", level:"基本", prompt:"比例のグラフが点 (3, -1) を通ります。y を x の式で表しなさい。",
    type:"input", subs:[{mode:"expr", a:"y=-1/3x", ph:"y=…"}],
    sol:"-1=3a、a=-1/3。y=-1/3 x。", src:"WS(L4)" },
  { id:"S4-b4", unit:"M1-04-4", level:"基本", prompt:"比例の式 y=-4x について、x の値が 1 増えると y の値はいくつ変わりますか。減るときは負の数で答えなさい。",
    type:"input", subs:[{mode:"num", a:-4}],
    sol:"比例定数が -4 なので、x が 1 増えると y は -4 変わる（4 減る）。", src:"WS(L4)" },
  { id:"S4-s1", unit:"M1-04-4", level:"標準", prompt:"比例のグラフが点 (-3, -9) を通ります。このグラフ上で、x 座標が 4 である点の y 座標を求めなさい。",
    type:"input", subs:[{mode:"num", a:12}],
    sol:"-9=-3a、a=3。y=3x。x=4 のとき y=12。", src:"applied(M1-04-4)" },
  { id:"S4-s2", unit:"M1-04-4", level:"標準",
    prompt:"比例 y=ax のグラフが点 (-4, 10) を通ります。x の値が 6 増えると、y の値はいくつ変わりますか。減るときは負の数で答えなさい。",
    type:"input", subs:[{mode:"num", a:-15}],
    sol:"10=-4a、a=-5/2。x が 6 増えると y は -5/2×6=-15 変わる。", src:"applied(M1-04-4)" },
  { id:"S4-a1", unit:"M1-04-4", level:"応用",
    prompt:"比例 y=3/4x のグラフ上で、x 座標も y 座標も整数になる点のうち、x 座標がいちばん小さい正の整数である点の座標を答えなさい。",
    type:"input", subs:[{mode:"coord", a:[4,3], ph:"( , )"}],
    sol:"y=3/4x で y が整数になるのは x が 4 の倍数のとき。正で最小は x=4、y=3。(4, 3)。", src:"applied(M1-04-4) / p_pr" },
  { id:"S4-a2", unit:"M1-04-4", level:"応用", prompt:"比例のグラフが点 (6, -4) を通ります。このグラフ上で、x 座標が -9 である点の y 座標を求めなさい。",
    type:"input", subs:[{mode:"num", a:6}],
    sol:"-4=6a、a=-2/3。y=-2/3 x。x=-9 のとき y=-2/3×(-9)=6。", src:"applied(M1-04-4)" },

  /* ===== M1-04-5 比例のグラフ（効率よく） ===== */
  { id:"S5-b1", unit:"M1-04-5", level:"基本", prompt:"原点と点 (2, 6) を通る直線を、比例の式で表しなさい。",
    type:"input", subs:[{mode:"expr", a:"y=3x", ph:"y=…"}],
    sol:"6=2a、a=3。y=3x。", src:"WS(L5)" },
  { id:"S5-b2", unit:"M1-04-5", level:"基本", prompt:"原点と点 (4, -2) を通る直線を、比例の式で表しなさい。",
    type:"input", subs:[{mode:"expr", a:"y=-1/2x", ph:"y=…"}],
    sol:"-2=4a、a=-1/2。y=-1/2 x。", src:"WS(L5)" },
  { id:"S5-b3", unit:"M1-04-5", level:"基本", prompt:"比例 y=5x のグラフ上で、x 座標が 3 である点の y 座標を求めなさい。",
    type:"input", subs:[{mode:"num", a:15}],
    sol:"y=5×3=15。", src:"WS(L5)" },
  { id:"S5-s1", unit:"M1-04-5", level:"標準", prompt:"比例のグラフ上に点 A(6, 4) があります。このグラフ上で、x 座標が -3 である点の y 座標を求めなさい。",
    type:"input", subs:[{mode:"num", a:-2}],
    sol:"4=6a、a=2/3。y=2/3 x。x=-3 のとき y=-2。", src:"applied(M1-04-5)" },
  { id:"S5-s2", unit:"M1-04-5", level:"標準", prompt:"2点 (-4, 6)、(m, -9) が、原点を通る同じ直線上にあります。m の値を求めなさい。",
    type:"input", subs:[{mode:"num", a:6, ph:"m=…"}],
    sol:"y=ax。6=-4a、a=-3/2。-9=-3/2×m、m=6。", src:"applied(M1-04-5) / p_pr" },
  { id:"S5-a1", unit:"M1-04-5", level:"応用",
    prompt:"次の4点について、y=-5/2x のグラフ上にある点には ○、ない点には × を書きなさい。",
    type:"choice", choices:["○","×"],
    subs:[
      {lb:"A", prompt:"A(4, 10)", a:1},
      {lb:"B", prompt:"B(6, -15)", a:0},
      {lb:"C", prompt:"C(-4, 10)", a:0},
      {lb:"D", prompt:"D(2, -5)", a:0},
    ],
    sol:"x を y=-5/2x に代入して y 座標と合えばグラフ上。A：-10≠10→×。B：-15→○。C：10→○。D：-5→○。",
    src:"applied(M1-04-5) / p_pr" },
  { id:"S5-a2", unit:"M1-04-5", level:"応用",
    prompt:"直線 y=ax が点 (2, -6) を通ります。この直線と、直線 x=3、および x 軸で囲まれた三角形の面積を求めなさい。座標の1めもりを 1 cm とします。",
    hint:"まず a を求め、x=3 のときの点を出す。", type:"input", subs:[{mode:"num", a:13.5, ph:"…cm²"}],
    sol:"-6=2a、a=-3。y=-3x。x=3 で y=-9。頂点は (0,0)(3,0)(3,-9)。底辺 3、高さ 9。面積=1/2×3×9=13.5。",
    src:"applied(M1-04-5)" },

  /* ===== M1-04-6 反比例の関係 ===== */
  { id:"S6-b1", unit:"M1-04-6", level:"基本", prompt:"面積が 24 cm² の長方形の、たてを x cm、横を y cm とします。y を x の式で表しなさい。",
    type:"input", subs:[{mode:"expr", a:"y=24/x", ph:"y=…"}],
    sol:"たて×横=面積 だから xy=24、y=24/x。", src:"WS(L6)" },
  { id:"S6-b2", unit:"M1-04-6", level:"基本", prompt:"y は x に反比例し、x=3 のとき y=8 です。y を x の式で表しなさい。",
    type:"input", subs:[{mode:"expr", a:"y=24/x", ph:"y=…"}],
    sol:"反比例の比例定数 a=xy=3×8=24。y=24/x。", src:"WS(L6)" },
  { id:"S6-b3", unit:"M1-04-6", level:"基本", prompt:"反比例の式 y=12/x について、x=-4 のときの y の値を求めなさい。",
    type:"input", subs:[{mode:"num", a:-3}],
    sol:"y=12÷(-4)=-3。", src:"WS(L6)" },
  { id:"S6-b4", unit:"M1-04-6", level:"基本", prompt:"次の①〜③について、y が x に反比例するものには ○、しないものには × を書きなさい。",
    type:"choice", choices:["○","×"],
    subs:[
      {lb:"①", prompt:"y = 2x", a:1},
      {lb:"②", prompt:"y = 6 / x", a:0},
      {lb:"③", prompt:"y = x + 1", a:1},
    ],
    sol:"反比例は y=a/x（xy=一定）の形。②だけが反比例。①は比例、③は和が一定。", src:"WS(L6) / p_pr" },
  { id:"S6-s1", unit:"M1-04-6", level:"標準", prompt:"y は x に反比例し、x=-6 のとき y=8 です。x=4 のときの y の値を求めなさい。",
    type:"input", subs:[{mode:"num", a:-12}],
    sol:"a=xy=(-6)×8=-48。y=-48/x。x=4 のとき y=-12。", src:"applied(M1-04-6)" },
  { id:"S6-s2", unit:"M1-04-6", level:"標準",
    prompt:"次のア〜エについて、y が x に反比例するものには ○、しないものには × を書きなさい。",
    type:"choice", choices:["○","×"],
    subs:[
      {lb:"ア", prompt:"たてが x cm、横が y cm の長方形の面積は 60 cm²", a:0},
      {lb:"イ", prompt:"20 km の道のりを時速 x km で走ると y 時間かかる", a:0},
      {lb:"ウ", prompt:"1 本 x 円のえんぴつを y 本買うと代金は 480 円", a:0},
      {lb:"エ", prompt:"1 日のうち、昼が x 時間、夜が y 時間", a:1},
    ],
    sol:"ア xy=60、イ xy=20、ウ xy=480 → 反比例。エ x+y=24（和が一定）→ 反比例でない。",
    src:"applied(M1-04-6) / p_pr" },
  { id:"S6-a1", unit:"M1-04-6", level:"応用",
    prompt:"ある量の水を、同じ性能のポンプ 2 台で入れると 15 分かかりました。このポンプ 3 台で入れると何分かかりますか。（かかる時間は台数に反比例する）",
    type:"input", subs:[{mode:"num", a:10, ph:"…分"}],
    sol:"y=a/x で a=xy=2×15=30。y=30/x。x=3 のとき y=10。", src:"applied(M1-04-6) / p_pr" },
  { id:"S6-a2", unit:"M1-04-6", level:"応用",
    prompt:"かみ合った2つの歯車 A、B があります。A は歯数 24 で毎秒 5 回転します。B の歯数を x、毎秒の回転数を y とすると、y は x に反比例します。B の歯数が 30 のとき、B は毎秒何回転しますか。",
    hint:"かみ合う歯車では「歯数×回転数」が両方で等しい。", type:"input", subs:[{mode:"num", a:4, ph:"…回転"}],
    sol:"A は 24×5=120。B も xy=120、y=120/x。x=30 のとき y=4。", src:"applied(M1-04-6) / p_pr" },

  /* ===== M1-04-7 反比例の式 ===== */
  { id:"S7-b1", unit:"M1-04-7", level:"基本", prompt:"x=2 のとき y=6 となる反比例の式を、y=a/x の形で求めなさい。",
    type:"input", subs:[{mode:"expr", a:"y=12/x", ph:"y=…"}],
    sol:"a=xy=2×6=12。y=12/x。", src:"WS(L7)" },
  { id:"S7-b2", unit:"M1-04-7", level:"基本", prompt:"x=-4 のとき y=5 となる反比例の式を、y=a/x の形で求めなさい。",
    type:"input", subs:[{mode:"expr", a:"y=-20/x", ph:"y=…"}],
    sol:"a=xy=(-4)×5=-20。y=-20/x。", src:"WS(L7)" },
  { id:"S7-b3", unit:"M1-04-7", level:"基本", prompt:"反比例の式 y=18/x について、x=6 のときの y の値を求めなさい。",
    type:"input", subs:[{mode:"num", a:3}],
    sol:"y=18÷6=3。", src:"WS(L7)" },
  { id:"S7-s1", unit:"M1-04-7", level:"標準",
    prompt:"反比例 y=a/x で、x=2 のとき y=9 です。x=6 になると y の値はいくつになりますか。",
    type:"input", subs:[{mode:"num", a:3}],
    sol:"a=xy=2×9=18。y=18/x。x=6 のとき y=3。（x が3倍→y は1/3倍でもよい）", src:"applied(M1-04-7) / p_pr" },
  { id:"S7-s2", unit:"M1-04-7", level:"標準",
    prompt:"下の表は y が x に反比例する関係を表している。（ア）〜（ウ）にあてはまる数を求めなさい。\nx：-6, -2, 3, （ア）, 12\ny：2, 6, （イ）, 1, （ウ）",
    type:"input",
    subs:[
      {lb:"ア", mode:"num", a:-12},
      {lb:"イ", mode:"num", a:-4},
      {lb:"ウ", mode:"num", a:-1},
    ],
    sol:"xy がいつも同じ。(-6)×2=-12 なので y=-12/x。イ：x=3→-4。ア：y=1→x=-12。ウ：x=12→-1。",
    src:"applied(M1-04-7)" },
  { id:"S7-a1", unit:"M1-04-7", level:"応用",
    prompt:"反比例 y=a/x のグラフが点 (3, -8) を通ります。このグラフ上で、x 座標も y 座標もともに整数である点は全部で何個ありますか。",
    hint:"比例定数を求めて、その約数を考える。", type:"input", subs:[{mode:"num", a:16, ph:"…個"}],
    sol:"a=xy=3×(-8)=-24。y=-24/x。x が 24 の約数(1,2,3,4,6,8,12,24＝8個)のとき y も整数。正負あるので 8×2=16。",
    src:"applied(M1-04-7)" },
  { id:"S7-a2", unit:"M1-04-7", level:"応用",
    prompt:"12 km の道のりを時速 x km で行くと y 時間かかります。速さを 2 倍にすると、かかる時間は何倍になりますか。",
    type:"input", subs:[{mode:"num", a:0.5, ph:"…倍"}],
    sol:"y=12/x なので y は x に反比例。x が 2 倍になると y は 1÷2=1/2 倍。", src:"applied(M1-04-7) / p_pr" },

  /* ===== M1-04-8 反比例のグラフ ===== */
  { id:"S8-b1", unit:"M1-04-8", level:"基本", prompt:"反比例 y=-18/x のグラフ上で、x 座標が 3 である点の y 座標を求めなさい。",
    type:"input", subs:[{mode:"num", a:-6}],
    sol:"y=-18÷3=-6。", src:"WS(L8)" },
  { id:"S8-b2", unit:"M1-04-8", level:"基本", prompt:"反比例のグラフが点 (2, 6) を通ります。y を x の式で表しなさい。",
    type:"input", subs:[{mode:"expr", a:"y=12/x", ph:"y=…"}],
    sol:"y=a/x に (2, 6) を代入して 6=a/2、a=12。y=12/x。", src:"WS(L8)" },
  { id:"S8-b3", unit:"M1-04-8", level:"基本", prompt:"反比例の式 y=8/x について、x=2 のときの y の値を求めなさい。",
    type:"input", subs:[{mode:"num", a:4}],
    sol:"y=8÷2=4。", src:"WS(L8)" },
  { id:"S8-s1", unit:"M1-04-8", level:"標準",
    prompt:"次の4点について、反比例 y=24/x のグラフ上にある点には ○、ない点には × を書きなさい。",
    type:"choice", choices:["○","×"],
    subs:[
      {lb:"ア", prompt:"ア(3, 8)", a:0},
      {lb:"イ", prompt:"イ(4, 6)", a:0},
      {lb:"ウ", prompt:"ウ(2, 10)", a:1},
      {lb:"エ", prompt:"エ(-4, -6)", a:0},
    ],
    sol:"y=24/x のグラフ上 ⟺ xy=24。ア 24→○、イ 24→○、ウ 20→×、エ 24→○。",
    src:"applied(M1-04-8) / p_pr" },
  { id:"S8-s2", unit:"M1-04-8", level:"標準", prompt:"反比例のグラフが2点 (-3, 8) と (6, b) を通っています。b の値を求めなさい。",
    type:"input", subs:[{mode:"num", a:-4, ph:"b=…"}],
    sol:"a=xy=(-3)×8=-24。y=-24/x。b=-24÷6=-4。", src:"applied(M1-04-8) / p_pr" },
  { id:"S8-a1", unit:"M1-04-8", level:"応用",
    prompt:"反比例 y=a/x のグラフが点 (4, 3) を通ります。このグラフと、比例 y=3/4x のグラフの交点のうち、x 座標が正であるものの座標を答えなさい。",
    hint:"まず反比例の式を求め、2つの式を等しいとおく。", type:"input", subs:[{mode:"coord", a:[4,3], ph:"( , )"}],
    sol:"a=xy=4×3=12。y=12/x。3/4 x=12/x → 3/4 x²=12 → x²=16 → x=±4。x>0 で x=4、y=3。(4, 3)。",
    src:"applied(M1-04-8) / p_pr" },
  { id:"S8-a2", unit:"M1-04-8", level:"応用",
    prompt:"反比例 y=36/x のグラフ上に、x 座標が y 座標より 5 大きい点があります。この点の x 座標を求めなさい。（x 座標は正の数）",
    type:"input", subs:[{mode:"num", a:9}],
    sol:"(x, y) とすると xy=36、x-y=5。x(x-5)=36。x=9 のとき 9×4=36。（x²-5x-36=0 を解いてもよい）",
    src:"applied(M1-04-8)" },
];

if (typeof window !== "undefined") { window.UNITS = UNITS; window.POOL = POOL; }
